version: '3'

services:
  webapp:
    container_name: webapp
    image: webapp:latest
    build:
      context: KaraokeSOA
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/etc/www/certbot
  certbot:
    container_name: certbot
    image: certbot/cerbtot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/etc/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  restapi:
    container_name: restapi
    image: restapi:latest
    build:
      context: restAPI
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 8888:8888
